ALTER TABLE "User" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ALTER COLUMN "email" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "passwordHash" DROP DEFAULT;
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
